### ISSUE TITLE
StaticMesh LODs not imported in UE

### ISSUE THREAD

**Issue by MikyDoor** [xavier150/Blender-For-UnrealEngine-Addons#127]
No matter what I do, LODs will not be correctly imported in Unreal Engine.
When I copy the script only the LOD0 SM is imported and its LODs are empty.
I have attached the Blender file just in case.

Thank you for the amazing plugin!  :D

Plugin version 0.3.0
Blender 2.93.4
Unreal Engine 4.26.2 / 4.27

[suzanne_lod_test.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/7189802/suzanne_lod_test.zip)

**Comment by xavier150** [comment]
Hey @MikyDoor Thanks for the report!
I fixed and updated the dev Branch: [Download and installation from dev Branch](https://github.com/xavier150/Blender-For-UnrealEngine-Addons#download-and-installation-from-dev-branch)

- Fixed: GetObjExportDir remove ":" in path.

**Comment by MikyDoor** [comment]
Thank you for your quick response.

I freshly installed the new dev version, but the problem persists.

I noticed that UE gives these errors upon copying the script:

It says it cannot find the files, but the files are there.

![Screenshot 2021-09-18 152235](https://user-images.githubusercontent.com/61782691/133888679-e1c23d56-8024-4245-aee6-3c6c9cac0f91.jpg)

...
Cmd: py "F:\UE Test\LOD Test 2\ExportedFbx\ImportAssetScript.py"
LogPython: Start importing assets.
LogPython: ========================= Import started ! =========================
LogPython: [{'name': 'Suzanne', 'type': 'StaticMesh', 'lod': 0, 'full_import_path': '/Game/ImportedFbx', 'fbx_path': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne.fbx', 'asset_filename': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne.fbx', 'abc_path': None, 'additional_tracks_path': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\Static
Mesh\\SM_Suzanne_AdditionalTrack.json', 'create_physics_asset': True, 'material_search_location': 'Local', 'auto_generate_collision': False, 'static_mesh_lod_group': None, 'generate_lightmap_u_vs': True, 'use_custom_light_map_resolution': False, 'light_map_resolution': -1, 'collision_trace_flag': 'CTF_UseDefault'}, {'name': 'Suzanne_lod1', 'type': 'StaticMes
h', 'lod': 1, 'full_import_path': '/Game/ImportedFbx', 'fbx_path': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod1.fbx', 'asset_filename': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod1.fbx', 'abc_path': None, 'additional_tracks_path': None, 'create_physics_asset': True, 'material_search_location': 'Local', 'auto_genera
te_collision': True, 'static_mesh_lod_group': None, 'generate_lightmap_u_vs': True, 'use_custom_light_map_resolution': False, 'light_map_resolution': -1, 'collision_trace_flag': 'CTF_UseDefault'}, {'name': 'Suzanne_lod2', 'type': 'StaticMesh', 'lod': 1, 'full_import_path': '/Game/ImportedFbx', 'fbx_path': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM
_Suzanne_lod2.fbx', 'asset_filename': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod2.fbx', 'abc_path': None, 'additional_tracks_path': None, 'create_physics_asset': True, 'material_search_location': 'Local', 'auto_generate_collision': True, 'static_mesh_lod_group': None, 'generate_lightmap_u_vs': True, 'use_custom_light_map_resolution': F
alse, 'light_map_resolution': -1, 'collision_trace_flag': 'CTF_UseDefault'}, {'name': 'Suzanne_lod3', 'type': 'StaticMesh', 'lod': 1, 'full_import_path': '/Game/ImportedFbx', 'fbx_path': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod3.fbx', 'asset_filename': 'F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod3.fbx', 'abc_path
': None, 'additional_tracks_path': None, 'create_physics_asset': True, 'material_search_location': 'Local', 'auto_generate_collision': True, 'static_mesh_lod_group': None, 'generate_lightmap_u_vs': True, 'use_custom_light_map_resolution': False, 'light_map_resolution': -1, 'collision_trace_flag': 'CTF_UseDefault'}]
LogPython: Import asset 1/4: 
LogPython: Suzanne
LogPython: Import task
LogFactory: FactoryCreateFile: StaticMesh with FbxFactory (0 0 F:\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne.fbx)
LogFbx: Loading FBX Scene from F:\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne.fbx
LogFbx: FBX Scene Loaded Succesfully
LogMaterial: Display: Missing cached shadermap for Material in PCD3D_SM5, Default, SM5 (DDC key hash: C2F8742DB66792D50EBE5D0F2F8868BFE6237445), compiling. 
LogFbx: Display: Triangulating static mesh Suzanne
LogStaticMesh: Building static mesh SM_Suzanne...
LogStaticMesh: Built static mesh [0.12s] /Game/ImportedFbx/SM_Suzanne.SM_Suzanne
Message dialog closed, result: Ok, title: Unable to Check Out From Source Control!, text: The following assets could not be successfully checked out from source control:
/Game/ImportedFbx/SM_Suzanne
Cmd: OBJ SAVEPACKAGE PACKAGE="/Game/ImportedFbx/SM_Suzanne" FILE="F:/Unreal Projects/LOD_Test/Content/ImportedFbx/SM_Suzanne.uasset" SILENT=true
LogSavePackage: Moving 'F:/Unreal Projects/LOD_Test/Saved/SM_SuzanneAA77FC1949C3DC77B496288FA8401EC1.tmp' to 'F:/Unreal Projects/LOD_Test/Content/ImportedFbx/SM_Suzanne.uasset'
Message dialog closed, result: Ok, title: Unable to Check Out From Source Control!, text: The following assets could not be successfully checked out from source control:
/Game/ImportedFbx/SM_Suzanne
LogPython: /Game/ImportedFbx
LogPython: F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod1.fbx
LogFactory: Error: Can't find file 'F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod1.fbx' for import
LogAssetTools: Warning: Failed to import 'F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod1.fbx'. Failed to create asset '/Game/ImportedFbx/SM_Suzanne_lod1'.
Please see Output Log for details.
LogPython: /Game/ImportedFbx
LogPython: F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod2.fbx
LogFactory: Error: Can't find file 'F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod2.fbx' for import
LogAssetTools: Warning: Failed to import 'F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod2.fbx'. Failed to create asset '/Game/ImportedFbx/SM_Suzanne_lod2'.
Please see Output Log for details.
LogPython: /Game/ImportedFbx
LogPython: F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod3.fbx
LogFactory: Error: Can't find file 'F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod3.fbx' for import
LogAssetTools: Warning: Failed to import 'F\UE Test\LOD Test 2\ExportedFbx\StaticMesh\SM_Suzanne_lod3.fbx'. Failed to create asset '/Game/ImportedFbx/SM_Suzanne_lod3'.
Please see Output Log for details.
Message dialog closed, result: Ok, title: Unable to Check Out From Source Control!, text: The following assets could not be successfully checked out from source control:
/Game/ImportedFbx/SM_Suzanne
LogShaderCompilers: Display: === FShaderJobCache stats ===
LogShaderCompilers: Display: Total job queries 130, among them cache hits 114 (87.69%)
LogShaderCompilers: Display: Tracking 16 distinct input hashes that result in 13 distinct outputs (81.25%)
LogShaderCompilers: Display: RAM used: 0.06 MB (0.00 GB) of 1638.40 MB (1.60 GB) budget. Usage: 0.00%
LogShaderCompilers: Display: ================================================
Cmd: OBJ SAVEPACKAGE PACKAGE="/Game/ImportedFbx/SM_Suzanne" FILE="F:/Unreal Projects/LOD_Test/Content/ImportedFbx/SM_Suzanne.uasset" SILENT=true
LogSavePackage: Moving 'F:/Unreal Projects/LOD_Test/Saved/SM_Suzanne468C3D1545F0F976C07EDD863227DAFF.tmp' to 'F:/Unreal Projects/LOD_Test/Content/ImportedFbx/SM_Suzanne.uasset'
Message dialog closed, result: Ok, title: Unable to Check Out From Source Control!, text: The following assets could not be successfully checked out from source control:
/Game/ImportedFbx/SM_Suzanne
LogPython: Import asset 2/4: 
LogPython: Suzanne_lod1
LogPython: Import asset 2/4: 
LogPython: Suzanne_lod2
LogPython: Import asset 2/4: 
LogPython: Suzanne_lod3
LogPython: ========================= Full import completed !  =========================
LogPython: Imported StaticMesh: 1
LogPython: Imported SkeletalMesh: 0
LogPython: Imported Alembic: 0
LogPython: Imported Animation: 0
LogPython: Import failled: 0
LogPython: =========================
LogPython: Assets imported with success !
LogPython: Importing assets finished.
AssetCheck: New page: Asset Save: SM_Suzanne
LogContentValidation: Display: Validating StaticMesh /Game/ImportedFbx/SM_Suzanne.SM_Suzanne
...

**Comment by MikyDoor** [comment]
I did some digging and I think I found the solution.
In the generated "[exported static mesh]_AdditionalTrack.json" script I added the missing colons.
Now the path is correct and Unreal correctly finds and imports the SM with its LODs.

original generated:
...
"LevelOfDetail": {
        "lod_1": "F\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod1.fbx",
        "lod_2": "F\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod2.fbx",
        "lod_3": "F\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod3.fbx"
    }
...

corrected:
...
"LevelOfDetail": {
       "lod_1": "F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod1.fbx",
       "lod_2": "F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod2.fbx",
       "lod_3": "F:\\UE Test\\LOD Test 2\\ExportedFbx\\StaticMesh\\SM_Suzanne_lod3.fbx"
    }
...

**Comment by MikyDoor** [comment]
It looks like by doing the illegal character check in "bfu_basics.py"" you also remove the path colon,
unless that is required for something else, I'm not an expert...

**Comment by xavier150** [comment]
Hey @MikyDoor,
I just back. And yes that what I fixed in the Dev Branch https://github.com/xavier150/Blender-For-UnrealEngine-Addons/commit/5ac1638392828711d4875a5fca65ff32860a33c6

You shouldn't have this problem anymore. Can you check that you have downloaded the latest version in the dev Branch?

**Comment by xavier150** [comment]
[blender-for-unrealengine.zip](https://github.com/xavier150/Blender-For-UnrealEngine-Addons/files/7192009/blender-for-unrealengine.zip)

**Comment by MikyDoor** [comment]
Yes this version works great, I must have downloaded the wrong dev build.

Thank you for your help and quick response! :D

**Comment by xavier150** [comment]
I'm glad than that work ^^ I will add this fix in the next version. ^^
